// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log_packet_struction.proto

#ifndef PROTOBUF_log_5fpacket_5fstruction_2eproto__INCLUDED
#define PROTOBUF_log_5fpacket_5fstruction_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "table.pb.h"
// @@protoc_insertion_point(includes)
namespace table {
class Column;
class ColumnDefaultTypeInternal;
extern ColumnDefaultTypeInternal _Column_default_instance_;
class Log_packet_struction;
class Log_packet_structionDefaultTypeInternal;
extern Log_packet_structionDefaultTypeInternal _Log_packet_struction_default_instance_;
class Log_packet_structionItem;
class Log_packet_structionItemDefaultTypeInternal;
extern Log_packet_structionItemDefaultTypeInternal _Log_packet_structionItem_default_instance_;
class Table;
class TableDefaultTypeInternal;
extern TableDefaultTypeInternal _Table_default_instance_;
class Wrapper;
class WrapperDefaultTypeInternal;
extern WrapperDefaultTypeInternal _Wrapper_default_instance_;
}  // namespace table

namespace table {

namespace protobuf_log_5fpacket_5fstruction_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_log_5fpacket_5fstruction_2eproto

// ===================================================================

class Log_packet_struction : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:table.Log_packet_struction) */ {
 public:
  Log_packet_struction();
  virtual ~Log_packet_struction();

  Log_packet_struction(const Log_packet_struction& from);

  inline Log_packet_struction& operator=(const Log_packet_struction& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Log_packet_struction& default_instance();

  static inline const Log_packet_struction* internal_default_instance() {
    return reinterpret_cast<const Log_packet_struction*>(
               &_Log_packet_struction_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(Log_packet_struction* other);

  // implements Message ----------------------------------------------

  inline Log_packet_struction* New() const PROTOBUF_FINAL { return New(NULL); }

  Log_packet_struction* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Log_packet_struction& from);
  void MergeFrom(const Log_packet_struction& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Log_packet_struction* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .table.Column columns = 2;
  int columns_size() const;
  void clear_columns();
  static const int kColumnsFieldNumber = 2;
  const ::table::Column& columns(int index) const;
  ::table::Column* mutable_columns(int index);
  ::table::Column* add_columns();
  ::google::protobuf::RepeatedPtrField< ::table::Column >*
      mutable_columns();
  const ::google::protobuf::RepeatedPtrField< ::table::Column >&
      columns() const;

  // repeated .table.Log_packet_structionItem items = 3;
  int items_size() const;
  void clear_items();
  static const int kItemsFieldNumber = 3;
  const ::table::Log_packet_structionItem& items(int index) const;
  ::table::Log_packet_structionItem* mutable_items(int index);
  ::table::Log_packet_structionItem* add_items();
  ::google::protobuf::RepeatedPtrField< ::table::Log_packet_structionItem >*
      mutable_items();
  const ::google::protobuf::RepeatedPtrField< ::table::Log_packet_structionItem >&
      items() const;

  // .table.Table table = 1;
  bool has_table() const;
  void clear_table();
  static const int kTableFieldNumber = 1;
  const ::table::Table& table() const;
  ::table::Table* mutable_table();
  ::table::Table* release_table();
  void set_allocated_table(::table::Table* table);

  // @@protoc_insertion_point(class_scope:table.Log_packet_struction)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::table::Column > columns_;
  ::google::protobuf::RepeatedPtrField< ::table::Log_packet_structionItem > items_;
  ::table::Table* table_;
  mutable int _cached_size_;
  friend struct protobuf_log_5fpacket_5fstruction_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Log_packet_structionItem : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:table.Log_packet_structionItem) */ {
 public:
  Log_packet_structionItem();
  virtual ~Log_packet_structionItem();

  Log_packet_structionItem(const Log_packet_structionItem& from);

  inline Log_packet_structionItem& operator=(const Log_packet_structionItem& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Log_packet_structionItem& default_instance();

  static inline const Log_packet_structionItem* internal_default_instance() {
    return reinterpret_cast<const Log_packet_structionItem*>(
               &_Log_packet_structionItem_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(Log_packet_structionItem* other);

  // implements Message ----------------------------------------------

  inline Log_packet_structionItem* New() const PROTOBUF_FINAL { return New(NULL); }

  Log_packet_structionItem* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Log_packet_structionItem& from);
  void MergeFrom(const Log_packet_structionItem& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Log_packet_structionItem* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // string description = 3;
  void clear_description();
  static const int kDescriptionFieldNumber = 3;
  const ::std::string& description() const;
  void set_description(const ::std::string& value);
  #if LANG_CXX11
  void set_description(::std::string&& value);
  #endif
  void set_description(const char* value);
  void set_description(const char* value, size_t size);
  ::std::string* mutable_description();
  ::std::string* release_description();
  void set_allocated_description(::std::string* description);

  // string key_name_for_code = 4;
  void clear_key_name_for_code();
  static const int kKeyNameForCodeFieldNumber = 4;
  const ::std::string& key_name_for_code() const;
  void set_key_name_for_code(const ::std::string& value);
  #if LANG_CXX11
  void set_key_name_for_code(::std::string&& value);
  #endif
  void set_key_name_for_code(const char* value);
  void set_key_name_for_code(const char* value, size_t size);
  ::std::string* mutable_key_name_for_code();
  ::std::string* release_key_name_for_code();
  void set_allocated_key_name_for_code(::std::string* key_name_for_code);

  // string key_type_for_code = 5;
  void clear_key_type_for_code();
  static const int kKeyTypeForCodeFieldNumber = 5;
  const ::std::string& key_type_for_code() const;
  void set_key_type_for_code(const ::std::string& value);
  #if LANG_CXX11
  void set_key_type_for_code(::std::string&& value);
  #endif
  void set_key_type_for_code(const char* value);
  void set_key_type_for_code(const char* value, size_t size);
  ::std::string* mutable_key_type_for_code();
  ::std::string* release_key_type_for_code();
  void set_allocated_key_type_for_code(::std::string* key_type_for_code);

  // int32 size = 2;
  void clear_size();
  static const int kSizeFieldNumber = 2;
  ::google::protobuf::int32 size() const;
  void set_size(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:table.Log_packet_structionItem)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr description_;
  ::google::protobuf::internal::ArenaStringPtr key_name_for_code_;
  ::google::protobuf::internal::ArenaStringPtr key_type_for_code_;
  ::google::protobuf::int32 size_;
  mutable int _cached_size_;
  friend struct protobuf_log_5fpacket_5fstruction_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Log_packet_struction

// .table.Table table = 1;
inline bool Log_packet_struction::has_table() const {
  return this != internal_default_instance() && table_ != NULL;
}
inline void Log_packet_struction::clear_table() {
  if (GetArenaNoVirtual() == NULL && table_ != NULL) delete table_;
  table_ = NULL;
}
inline const ::table::Table& Log_packet_struction::table() const {
  // @@protoc_insertion_point(field_get:table.Log_packet_struction.table)
  return table_ != NULL ? *table_
                         : *::table::Table::internal_default_instance();
}
inline ::table::Table* Log_packet_struction::mutable_table() {
  
  if (table_ == NULL) {
    table_ = new ::table::Table;
  }
  // @@protoc_insertion_point(field_mutable:table.Log_packet_struction.table)
  return table_;
}
inline ::table::Table* Log_packet_struction::release_table() {
  // @@protoc_insertion_point(field_release:table.Log_packet_struction.table)
  
  ::table::Table* temp = table_;
  table_ = NULL;
  return temp;
}
inline void Log_packet_struction::set_allocated_table(::table::Table* table) {
  delete table_;
  table_ = table;
  if (table) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:table.Log_packet_struction.table)
}

// repeated .table.Column columns = 2;
inline int Log_packet_struction::columns_size() const {
  return columns_.size();
}
inline void Log_packet_struction::clear_columns() {
  columns_.Clear();
}
inline const ::table::Column& Log_packet_struction::columns(int index) const {
  // @@protoc_insertion_point(field_get:table.Log_packet_struction.columns)
  return columns_.Get(index);
}
inline ::table::Column* Log_packet_struction::mutable_columns(int index) {
  // @@protoc_insertion_point(field_mutable:table.Log_packet_struction.columns)
  return columns_.Mutable(index);
}
inline ::table::Column* Log_packet_struction::add_columns() {
  // @@protoc_insertion_point(field_add:table.Log_packet_struction.columns)
  return columns_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::table::Column >*
Log_packet_struction::mutable_columns() {
  // @@protoc_insertion_point(field_mutable_list:table.Log_packet_struction.columns)
  return &columns_;
}
inline const ::google::protobuf::RepeatedPtrField< ::table::Column >&
Log_packet_struction::columns() const {
  // @@protoc_insertion_point(field_list:table.Log_packet_struction.columns)
  return columns_;
}

// repeated .table.Log_packet_structionItem items = 3;
inline int Log_packet_struction::items_size() const {
  return items_.size();
}
inline void Log_packet_struction::clear_items() {
  items_.Clear();
}
inline const ::table::Log_packet_structionItem& Log_packet_struction::items(int index) const {
  // @@protoc_insertion_point(field_get:table.Log_packet_struction.items)
  return items_.Get(index);
}
inline ::table::Log_packet_structionItem* Log_packet_struction::mutable_items(int index) {
  // @@protoc_insertion_point(field_mutable:table.Log_packet_struction.items)
  return items_.Mutable(index);
}
inline ::table::Log_packet_structionItem* Log_packet_struction::add_items() {
  // @@protoc_insertion_point(field_add:table.Log_packet_struction.items)
  return items_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::table::Log_packet_structionItem >*
Log_packet_struction::mutable_items() {
  // @@protoc_insertion_point(field_mutable_list:table.Log_packet_struction.items)
  return &items_;
}
inline const ::google::protobuf::RepeatedPtrField< ::table::Log_packet_structionItem >&
Log_packet_struction::items() const {
  // @@protoc_insertion_point(field_list:table.Log_packet_struction.items)
  return items_;
}

// -------------------------------------------------------------------

// Log_packet_structionItem

// string name = 1;
inline void Log_packet_structionItem::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Log_packet_structionItem::name() const {
  // @@protoc_insertion_point(field_get:table.Log_packet_structionItem.name)
  return name_.GetNoArena();
}
inline void Log_packet_structionItem::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:table.Log_packet_structionItem.name)
}
#if LANG_CXX11
inline void Log_packet_structionItem::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:table.Log_packet_structionItem.name)
}
#endif
inline void Log_packet_structionItem::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:table.Log_packet_structionItem.name)
}
inline void Log_packet_structionItem::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:table.Log_packet_structionItem.name)
}
inline ::std::string* Log_packet_structionItem::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:table.Log_packet_structionItem.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Log_packet_structionItem::release_name() {
  // @@protoc_insertion_point(field_release:table.Log_packet_structionItem.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Log_packet_structionItem::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:table.Log_packet_structionItem.name)
}

// int32 size = 2;
inline void Log_packet_structionItem::clear_size() {
  size_ = 0;
}
inline ::google::protobuf::int32 Log_packet_structionItem::size() const {
  // @@protoc_insertion_point(field_get:table.Log_packet_structionItem.size)
  return size_;
}
inline void Log_packet_structionItem::set_size(::google::protobuf::int32 value) {
  
  size_ = value;
  // @@protoc_insertion_point(field_set:table.Log_packet_structionItem.size)
}

// string description = 3;
inline void Log_packet_structionItem::clear_description() {
  description_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Log_packet_structionItem::description() const {
  // @@protoc_insertion_point(field_get:table.Log_packet_structionItem.description)
  return description_.GetNoArena();
}
inline void Log_packet_structionItem::set_description(const ::std::string& value) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:table.Log_packet_structionItem.description)
}
#if LANG_CXX11
inline void Log_packet_structionItem::set_description(::std::string&& value) {
  
  description_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:table.Log_packet_structionItem.description)
}
#endif
inline void Log_packet_structionItem::set_description(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:table.Log_packet_structionItem.description)
}
inline void Log_packet_structionItem::set_description(const char* value, size_t size) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:table.Log_packet_structionItem.description)
}
inline ::std::string* Log_packet_structionItem::mutable_description() {
  
  // @@protoc_insertion_point(field_mutable:table.Log_packet_structionItem.description)
  return description_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Log_packet_structionItem::release_description() {
  // @@protoc_insertion_point(field_release:table.Log_packet_structionItem.description)
  
  return description_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Log_packet_structionItem::set_allocated_description(::std::string* description) {
  if (description != NULL) {
    
  } else {
    
  }
  description_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), description);
  // @@protoc_insertion_point(field_set_allocated:table.Log_packet_structionItem.description)
}

// string key_name_for_code = 4;
inline void Log_packet_structionItem::clear_key_name_for_code() {
  key_name_for_code_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Log_packet_structionItem::key_name_for_code() const {
  // @@protoc_insertion_point(field_get:table.Log_packet_structionItem.key_name_for_code)
  return key_name_for_code_.GetNoArena();
}
inline void Log_packet_structionItem::set_key_name_for_code(const ::std::string& value) {
  
  key_name_for_code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:table.Log_packet_structionItem.key_name_for_code)
}
#if LANG_CXX11
inline void Log_packet_structionItem::set_key_name_for_code(::std::string&& value) {
  
  key_name_for_code_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:table.Log_packet_structionItem.key_name_for_code)
}
#endif
inline void Log_packet_structionItem::set_key_name_for_code(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  key_name_for_code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:table.Log_packet_structionItem.key_name_for_code)
}
inline void Log_packet_structionItem::set_key_name_for_code(const char* value, size_t size) {
  
  key_name_for_code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:table.Log_packet_structionItem.key_name_for_code)
}
inline ::std::string* Log_packet_structionItem::mutable_key_name_for_code() {
  
  // @@protoc_insertion_point(field_mutable:table.Log_packet_structionItem.key_name_for_code)
  return key_name_for_code_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Log_packet_structionItem::release_key_name_for_code() {
  // @@protoc_insertion_point(field_release:table.Log_packet_structionItem.key_name_for_code)
  
  return key_name_for_code_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Log_packet_structionItem::set_allocated_key_name_for_code(::std::string* key_name_for_code) {
  if (key_name_for_code != NULL) {
    
  } else {
    
  }
  key_name_for_code_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key_name_for_code);
  // @@protoc_insertion_point(field_set_allocated:table.Log_packet_structionItem.key_name_for_code)
}

// string key_type_for_code = 5;
inline void Log_packet_structionItem::clear_key_type_for_code() {
  key_type_for_code_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Log_packet_structionItem::key_type_for_code() const {
  // @@protoc_insertion_point(field_get:table.Log_packet_structionItem.key_type_for_code)
  return key_type_for_code_.GetNoArena();
}
inline void Log_packet_structionItem::set_key_type_for_code(const ::std::string& value) {
  
  key_type_for_code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:table.Log_packet_structionItem.key_type_for_code)
}
#if LANG_CXX11
inline void Log_packet_structionItem::set_key_type_for_code(::std::string&& value) {
  
  key_type_for_code_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:table.Log_packet_structionItem.key_type_for_code)
}
#endif
inline void Log_packet_structionItem::set_key_type_for_code(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  key_type_for_code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:table.Log_packet_structionItem.key_type_for_code)
}
inline void Log_packet_structionItem::set_key_type_for_code(const char* value, size_t size) {
  
  key_type_for_code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:table.Log_packet_structionItem.key_type_for_code)
}
inline ::std::string* Log_packet_structionItem::mutable_key_type_for_code() {
  
  // @@protoc_insertion_point(field_mutable:table.Log_packet_structionItem.key_type_for_code)
  return key_type_for_code_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Log_packet_structionItem::release_key_type_for_code() {
  // @@protoc_insertion_point(field_release:table.Log_packet_structionItem.key_type_for_code)
  
  return key_type_for_code_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Log_packet_structionItem::set_allocated_key_type_for_code(::std::string* key_type_for_code) {
  if (key_type_for_code != NULL) {
    
  } else {
    
  }
  key_type_for_code_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key_type_for_code);
  // @@protoc_insertion_point(field_set_allocated:table.Log_packet_structionItem.key_type_for_code)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace table

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_log_5fpacket_5fstruction_2eproto__INCLUDED
