// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packet_id_allocate.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "packet_id_allocate.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace table {
class Packet_id_allocateDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Packet_id_allocate> {
} _Packet_id_allocate_default_instance_;
class Packet_id_allocateItemDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Packet_id_allocateItem> {
} _Packet_id_allocateItem_default_instance_;

namespace protobuf_packet_5fid_5fallocate_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[2];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Packet_id_allocate, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Packet_id_allocate, table_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Packet_id_allocate, columns_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Packet_id_allocate, items_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Packet_id_allocateItem, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Packet_id_allocateItem, id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Packet_id_allocateItem, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Packet_id_allocateItem, description_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Packet_id_allocateItem, packet_struction_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(Packet_id_allocate)},
  { 8, -1, sizeof(Packet_id_allocateItem)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_Packet_id_allocate_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_Packet_id_allocateItem_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "packet_id_allocate.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

}  // namespace

void TableStruct::Shutdown() {
  _Packet_id_allocate_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _Packet_id_allocateItem_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  ::table::protobuf_table_2eproto::InitDefaults();
  _Packet_id_allocate_default_instance_.DefaultConstruct();
  _Packet_id_allocateItem_default_instance_.DefaultConstruct();
  _Packet_id_allocate_default_instance_.get_mutable()->table_ = const_cast< ::table::Table*>(
      ::table::Table::internal_default_instance());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\030packet_id_allocate.proto\022\005table\032\013table"
      ".proto\"\177\n\022Packet_id_allocate\022\033\n\005table\030\001 "
      "\001(\0132\014.table.Table\022\036\n\007columns\030\002 \003(\0132\r.tab"
      "le.Column\022,\n\005items\030\003 \003(\0132\035.table.Packet_"
      "id_allocateItem\"a\n\026Packet_id_allocateIte"
      "m\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\023\n\013descripti"
      "on\030\003 \001(\t\022\030\n\020packet_struction\030\004 \001(\tb\006prot"
      "o3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 282);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "packet_id_allocate.proto", &protobuf_RegisterTypes);
  ::table::protobuf_table_2eproto::AddDescriptors();
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_packet_5fid_5fallocate_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Packet_id_allocate::kTableFieldNumber;
const int Packet_id_allocate::kColumnsFieldNumber;
const int Packet_id_allocate::kItemsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Packet_id_allocate::Packet_id_allocate()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_packet_5fid_5fallocate_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:table.Packet_id_allocate)
}
Packet_id_allocate::Packet_id_allocate(const Packet_id_allocate& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      columns_(from.columns_),
      items_(from.items_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_table()) {
    table_ = new ::table::Table(*from.table_);
  } else {
    table_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:table.Packet_id_allocate)
}

void Packet_id_allocate::SharedCtor() {
  table_ = NULL;
  _cached_size_ = 0;
}

Packet_id_allocate::~Packet_id_allocate() {
  // @@protoc_insertion_point(destructor:table.Packet_id_allocate)
  SharedDtor();
}

void Packet_id_allocate::SharedDtor() {
  if (this != internal_default_instance()) {
    delete table_;
  }
}

void Packet_id_allocate::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Packet_id_allocate::descriptor() {
  protobuf_packet_5fid_5fallocate_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_packet_5fid_5fallocate_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Packet_id_allocate& Packet_id_allocate::default_instance() {
  protobuf_packet_5fid_5fallocate_2eproto::InitDefaults();
  return *internal_default_instance();
}

Packet_id_allocate* Packet_id_allocate::New(::google::protobuf::Arena* arena) const {
  Packet_id_allocate* n = new Packet_id_allocate;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Packet_id_allocate::Clear() {
// @@protoc_insertion_point(message_clear_start:table.Packet_id_allocate)
  columns_.Clear();
  items_.Clear();
  if (GetArenaNoVirtual() == NULL && table_ != NULL) {
    delete table_;
  }
  table_ = NULL;
}

bool Packet_id_allocate::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:table.Packet_id_allocate)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .table.Table table = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_table()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .table.Column columns = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_columns()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .table.Packet_id_allocateItem items = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_items()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:table.Packet_id_allocate)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:table.Packet_id_allocate)
  return false;
#undef DO_
}

void Packet_id_allocate::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:table.Packet_id_allocate)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .table.Table table = 1;
  if (this->has_table()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->table_, output);
  }

  // repeated .table.Column columns = 2;
  for (unsigned int i = 0, n = this->columns_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->columns(i), output);
  }

  // repeated .table.Packet_id_allocateItem items = 3;
  for (unsigned int i = 0, n = this->items_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->items(i), output);
  }

  // @@protoc_insertion_point(serialize_end:table.Packet_id_allocate)
}

::google::protobuf::uint8* Packet_id_allocate::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:table.Packet_id_allocate)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .table.Table table = 1;
  if (this->has_table()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->table_, deterministic, target);
  }

  // repeated .table.Column columns = 2;
  for (unsigned int i = 0, n = this->columns_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, this->columns(i), deterministic, target);
  }

  // repeated .table.Packet_id_allocateItem items = 3;
  for (unsigned int i = 0, n = this->items_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        3, this->items(i), deterministic, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:table.Packet_id_allocate)
  return target;
}

size_t Packet_id_allocate::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:table.Packet_id_allocate)
  size_t total_size = 0;

  // repeated .table.Column columns = 2;
  {
    unsigned int count = this->columns_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->columns(i));
    }
  }

  // repeated .table.Packet_id_allocateItem items = 3;
  {
    unsigned int count = this->items_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->items(i));
    }
  }

  // .table.Table table = 1;
  if (this->has_table()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->table_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Packet_id_allocate::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:table.Packet_id_allocate)
  GOOGLE_DCHECK_NE(&from, this);
  const Packet_id_allocate* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Packet_id_allocate>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:table.Packet_id_allocate)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:table.Packet_id_allocate)
    MergeFrom(*source);
  }
}

void Packet_id_allocate::MergeFrom(const Packet_id_allocate& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:table.Packet_id_allocate)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  columns_.MergeFrom(from.columns_);
  items_.MergeFrom(from.items_);
  if (from.has_table()) {
    mutable_table()->::table::Table::MergeFrom(from.table());
  }
}

void Packet_id_allocate::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:table.Packet_id_allocate)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Packet_id_allocate::CopyFrom(const Packet_id_allocate& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:table.Packet_id_allocate)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Packet_id_allocate::IsInitialized() const {
  return true;
}

void Packet_id_allocate::Swap(Packet_id_allocate* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Packet_id_allocate::InternalSwap(Packet_id_allocate* other) {
  columns_.InternalSwap(&other->columns_);
  items_.InternalSwap(&other->items_);
  std::swap(table_, other->table_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Packet_id_allocate::GetMetadata() const {
  protobuf_packet_5fid_5fallocate_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_packet_5fid_5fallocate_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Packet_id_allocate

// .table.Table table = 1;
bool Packet_id_allocate::has_table() const {
  return this != internal_default_instance() && table_ != NULL;
}
void Packet_id_allocate::clear_table() {
  if (GetArenaNoVirtual() == NULL && table_ != NULL) delete table_;
  table_ = NULL;
}
const ::table::Table& Packet_id_allocate::table() const {
  // @@protoc_insertion_point(field_get:table.Packet_id_allocate.table)
  return table_ != NULL ? *table_
                         : *::table::Table::internal_default_instance();
}
::table::Table* Packet_id_allocate::mutable_table() {
  
  if (table_ == NULL) {
    table_ = new ::table::Table;
  }
  // @@protoc_insertion_point(field_mutable:table.Packet_id_allocate.table)
  return table_;
}
::table::Table* Packet_id_allocate::release_table() {
  // @@protoc_insertion_point(field_release:table.Packet_id_allocate.table)
  
  ::table::Table* temp = table_;
  table_ = NULL;
  return temp;
}
void Packet_id_allocate::set_allocated_table(::table::Table* table) {
  delete table_;
  table_ = table;
  if (table) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:table.Packet_id_allocate.table)
}

// repeated .table.Column columns = 2;
int Packet_id_allocate::columns_size() const {
  return columns_.size();
}
void Packet_id_allocate::clear_columns() {
  columns_.Clear();
}
const ::table::Column& Packet_id_allocate::columns(int index) const {
  // @@protoc_insertion_point(field_get:table.Packet_id_allocate.columns)
  return columns_.Get(index);
}
::table::Column* Packet_id_allocate::mutable_columns(int index) {
  // @@protoc_insertion_point(field_mutable:table.Packet_id_allocate.columns)
  return columns_.Mutable(index);
}
::table::Column* Packet_id_allocate::add_columns() {
  // @@protoc_insertion_point(field_add:table.Packet_id_allocate.columns)
  return columns_.Add();
}
::google::protobuf::RepeatedPtrField< ::table::Column >*
Packet_id_allocate::mutable_columns() {
  // @@protoc_insertion_point(field_mutable_list:table.Packet_id_allocate.columns)
  return &columns_;
}
const ::google::protobuf::RepeatedPtrField< ::table::Column >&
Packet_id_allocate::columns() const {
  // @@protoc_insertion_point(field_list:table.Packet_id_allocate.columns)
  return columns_;
}

// repeated .table.Packet_id_allocateItem items = 3;
int Packet_id_allocate::items_size() const {
  return items_.size();
}
void Packet_id_allocate::clear_items() {
  items_.Clear();
}
const ::table::Packet_id_allocateItem& Packet_id_allocate::items(int index) const {
  // @@protoc_insertion_point(field_get:table.Packet_id_allocate.items)
  return items_.Get(index);
}
::table::Packet_id_allocateItem* Packet_id_allocate::mutable_items(int index) {
  // @@protoc_insertion_point(field_mutable:table.Packet_id_allocate.items)
  return items_.Mutable(index);
}
::table::Packet_id_allocateItem* Packet_id_allocate::add_items() {
  // @@protoc_insertion_point(field_add:table.Packet_id_allocate.items)
  return items_.Add();
}
::google::protobuf::RepeatedPtrField< ::table::Packet_id_allocateItem >*
Packet_id_allocate::mutable_items() {
  // @@protoc_insertion_point(field_mutable_list:table.Packet_id_allocate.items)
  return &items_;
}
const ::google::protobuf::RepeatedPtrField< ::table::Packet_id_allocateItem >&
Packet_id_allocate::items() const {
  // @@protoc_insertion_point(field_list:table.Packet_id_allocate.items)
  return items_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Packet_id_allocateItem::kIdFieldNumber;
const int Packet_id_allocateItem::kNameFieldNumber;
const int Packet_id_allocateItem::kDescriptionFieldNumber;
const int Packet_id_allocateItem::kPacketStructionFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Packet_id_allocateItem::Packet_id_allocateItem()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_packet_5fid_5fallocate_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:table.Packet_id_allocateItem)
}
Packet_id_allocateItem::Packet_id_allocateItem(const Packet_id_allocateItem& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  description_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.description().size() > 0) {
    description_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.description_);
  }
  packet_struction_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.packet_struction().size() > 0) {
    packet_struction_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.packet_struction_);
  }
  id_ = from.id_;
  // @@protoc_insertion_point(copy_constructor:table.Packet_id_allocateItem)
}

void Packet_id_allocateItem::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  description_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  packet_struction_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  id_ = 0;
  _cached_size_ = 0;
}

Packet_id_allocateItem::~Packet_id_allocateItem() {
  // @@protoc_insertion_point(destructor:table.Packet_id_allocateItem)
  SharedDtor();
}

void Packet_id_allocateItem::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  description_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  packet_struction_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Packet_id_allocateItem::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Packet_id_allocateItem::descriptor() {
  protobuf_packet_5fid_5fallocate_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_packet_5fid_5fallocate_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Packet_id_allocateItem& Packet_id_allocateItem::default_instance() {
  protobuf_packet_5fid_5fallocate_2eproto::InitDefaults();
  return *internal_default_instance();
}

Packet_id_allocateItem* Packet_id_allocateItem::New(::google::protobuf::Arena* arena) const {
  Packet_id_allocateItem* n = new Packet_id_allocateItem;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Packet_id_allocateItem::Clear() {
// @@protoc_insertion_point(message_clear_start:table.Packet_id_allocateItem)
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  description_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  packet_struction_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  id_ = 0;
}

bool Packet_id_allocateItem::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:table.Packet_id_allocateItem)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string name = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "table.Packet_id_allocateItem.name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string description = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_description()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->description().data(), this->description().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "table.Packet_id_allocateItem.description"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string packet_struction = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_packet_struction()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->packet_struction().data(), this->packet_struction().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "table.Packet_id_allocateItem.packet_struction"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:table.Packet_id_allocateItem)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:table.Packet_id_allocateItem)
  return false;
#undef DO_
}

void Packet_id_allocateItem::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:table.Packet_id_allocateItem)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->id(), output);
  }

  // string name = 2;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "table.Packet_id_allocateItem.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->name(), output);
  }

  // string description = 3;
  if (this->description().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->description().data(), this->description().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "table.Packet_id_allocateItem.description");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->description(), output);
  }

  // string packet_struction = 4;
  if (this->packet_struction().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->packet_struction().data(), this->packet_struction().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "table.Packet_id_allocateItem.packet_struction");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->packet_struction(), output);
  }

  // @@protoc_insertion_point(serialize_end:table.Packet_id_allocateItem)
}

::google::protobuf::uint8* Packet_id_allocateItem::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:table.Packet_id_allocateItem)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->id(), target);
  }

  // string name = 2;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "table.Packet_id_allocateItem.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->name(), target);
  }

  // string description = 3;
  if (this->description().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->description().data(), this->description().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "table.Packet_id_allocateItem.description");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->description(), target);
  }

  // string packet_struction = 4;
  if (this->packet_struction().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->packet_struction().data(), this->packet_struction().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "table.Packet_id_allocateItem.packet_struction");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->packet_struction(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:table.Packet_id_allocateItem)
  return target;
}

size_t Packet_id_allocateItem::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:table.Packet_id_allocateItem)
  size_t total_size = 0;

  // string name = 2;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // string description = 3;
  if (this->description().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->description());
  }

  // string packet_struction = 4;
  if (this->packet_struction().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->packet_struction());
  }

  // int32 id = 1;
  if (this->id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Packet_id_allocateItem::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:table.Packet_id_allocateItem)
  GOOGLE_DCHECK_NE(&from, this);
  const Packet_id_allocateItem* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Packet_id_allocateItem>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:table.Packet_id_allocateItem)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:table.Packet_id_allocateItem)
    MergeFrom(*source);
  }
}

void Packet_id_allocateItem::MergeFrom(const Packet_id_allocateItem& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:table.Packet_id_allocateItem)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.description().size() > 0) {

    description_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.description_);
  }
  if (from.packet_struction().size() > 0) {

    packet_struction_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.packet_struction_);
  }
  if (from.id() != 0) {
    set_id(from.id());
  }
}

void Packet_id_allocateItem::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:table.Packet_id_allocateItem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Packet_id_allocateItem::CopyFrom(const Packet_id_allocateItem& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:table.Packet_id_allocateItem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Packet_id_allocateItem::IsInitialized() const {
  return true;
}

void Packet_id_allocateItem::Swap(Packet_id_allocateItem* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Packet_id_allocateItem::InternalSwap(Packet_id_allocateItem* other) {
  name_.Swap(&other->name_);
  description_.Swap(&other->description_);
  packet_struction_.Swap(&other->packet_struction_);
  std::swap(id_, other->id_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Packet_id_allocateItem::GetMetadata() const {
  protobuf_packet_5fid_5fallocate_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_packet_5fid_5fallocate_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Packet_id_allocateItem

// int32 id = 1;
void Packet_id_allocateItem::clear_id() {
  id_ = 0;
}
::google::protobuf::int32 Packet_id_allocateItem::id() const {
  // @@protoc_insertion_point(field_get:table.Packet_id_allocateItem.id)
  return id_;
}
void Packet_id_allocateItem::set_id(::google::protobuf::int32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:table.Packet_id_allocateItem.id)
}

// string name = 2;
void Packet_id_allocateItem::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& Packet_id_allocateItem::name() const {
  // @@protoc_insertion_point(field_get:table.Packet_id_allocateItem.name)
  return name_.GetNoArena();
}
void Packet_id_allocateItem::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:table.Packet_id_allocateItem.name)
}
#if LANG_CXX11
void Packet_id_allocateItem::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:table.Packet_id_allocateItem.name)
}
#endif
void Packet_id_allocateItem::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:table.Packet_id_allocateItem.name)
}
void Packet_id_allocateItem::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:table.Packet_id_allocateItem.name)
}
::std::string* Packet_id_allocateItem::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:table.Packet_id_allocateItem.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* Packet_id_allocateItem::release_name() {
  // @@protoc_insertion_point(field_release:table.Packet_id_allocateItem.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void Packet_id_allocateItem::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:table.Packet_id_allocateItem.name)
}

// string description = 3;
void Packet_id_allocateItem::clear_description() {
  description_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& Packet_id_allocateItem::description() const {
  // @@protoc_insertion_point(field_get:table.Packet_id_allocateItem.description)
  return description_.GetNoArena();
}
void Packet_id_allocateItem::set_description(const ::std::string& value) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:table.Packet_id_allocateItem.description)
}
#if LANG_CXX11
void Packet_id_allocateItem::set_description(::std::string&& value) {
  
  description_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:table.Packet_id_allocateItem.description)
}
#endif
void Packet_id_allocateItem::set_description(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:table.Packet_id_allocateItem.description)
}
void Packet_id_allocateItem::set_description(const char* value, size_t size) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:table.Packet_id_allocateItem.description)
}
::std::string* Packet_id_allocateItem::mutable_description() {
  
  // @@protoc_insertion_point(field_mutable:table.Packet_id_allocateItem.description)
  return description_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* Packet_id_allocateItem::release_description() {
  // @@protoc_insertion_point(field_release:table.Packet_id_allocateItem.description)
  
  return description_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void Packet_id_allocateItem::set_allocated_description(::std::string* description) {
  if (description != NULL) {
    
  } else {
    
  }
  description_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), description);
  // @@protoc_insertion_point(field_set_allocated:table.Packet_id_allocateItem.description)
}

// string packet_struction = 4;
void Packet_id_allocateItem::clear_packet_struction() {
  packet_struction_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& Packet_id_allocateItem::packet_struction() const {
  // @@protoc_insertion_point(field_get:table.Packet_id_allocateItem.packet_struction)
  return packet_struction_.GetNoArena();
}
void Packet_id_allocateItem::set_packet_struction(const ::std::string& value) {
  
  packet_struction_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:table.Packet_id_allocateItem.packet_struction)
}
#if LANG_CXX11
void Packet_id_allocateItem::set_packet_struction(::std::string&& value) {
  
  packet_struction_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:table.Packet_id_allocateItem.packet_struction)
}
#endif
void Packet_id_allocateItem::set_packet_struction(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  packet_struction_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:table.Packet_id_allocateItem.packet_struction)
}
void Packet_id_allocateItem::set_packet_struction(const char* value, size_t size) {
  
  packet_struction_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:table.Packet_id_allocateItem.packet_struction)
}
::std::string* Packet_id_allocateItem::mutable_packet_struction() {
  
  // @@protoc_insertion_point(field_mutable:table.Packet_id_allocateItem.packet_struction)
  return packet_struction_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* Packet_id_allocateItem::release_packet_struction() {
  // @@protoc_insertion_point(field_release:table.Packet_id_allocateItem.packet_struction)
  
  return packet_struction_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void Packet_id_allocateItem::set_allocated_packet_struction(::std::string* packet_struction) {
  if (packet_struction != NULL) {
    
  } else {
    
  }
  packet_struction_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), packet_struction);
  // @@protoc_insertion_point(field_set_allocated:table.Packet_id_allocateItem.packet_struction)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace table

// @@protoc_insertion_point(global_scope)
