# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: packet_id_allocate.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import table_pb2 as table__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='packet_id_allocate.proto',
  package='table',
  syntax='proto3',
  serialized_pb=_b('\n\x18packet_id_allocate.proto\x12\x05table\x1a\x0btable.proto\"\x7f\n\x12Packet_id_allocate\x12\x1b\n\x05table\x18\x01 \x01(\x0b\x32\x0c.table.Table\x12\x1e\n\x07\x63olumns\x18\x02 \x03(\x0b\x32\r.table.Column\x12,\n\x05items\x18\x03 \x03(\x0b\x32\x1d.table.Packet_id_allocateItem\"a\n\x16Packet_id_allocateItem\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x18\n\x10packet_struction\x18\x04 \x01(\tb\x06proto3')
  ,
  dependencies=[table__pb2.DESCRIPTOR,])




_PACKET_ID_ALLOCATE = _descriptor.Descriptor(
  name='Packet_id_allocate',
  full_name='table.Packet_id_allocate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='table', full_name='table.Packet_id_allocate.table', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='columns', full_name='table.Packet_id_allocate.columns', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='items', full_name='table.Packet_id_allocate.items', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=175,
)


_PACKET_ID_ALLOCATEITEM = _descriptor.Descriptor(
  name='Packet_id_allocateItem',
  full_name='table.Packet_id_allocateItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='table.Packet_id_allocateItem.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='table.Packet_id_allocateItem.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='table.Packet_id_allocateItem.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='packet_struction', full_name='table.Packet_id_allocateItem.packet_struction', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=274,
)

_PACKET_ID_ALLOCATE.fields_by_name['table'].message_type = table__pb2._TABLE
_PACKET_ID_ALLOCATE.fields_by_name['columns'].message_type = table__pb2._COLUMN
_PACKET_ID_ALLOCATE.fields_by_name['items'].message_type = _PACKET_ID_ALLOCATEITEM
DESCRIPTOR.message_types_by_name['Packet_id_allocate'] = _PACKET_ID_ALLOCATE
DESCRIPTOR.message_types_by_name['Packet_id_allocateItem'] = _PACKET_ID_ALLOCATEITEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Packet_id_allocate = _reflection.GeneratedProtocolMessageType('Packet_id_allocate', (_message.Message,), dict(
  DESCRIPTOR = _PACKET_ID_ALLOCATE,
  __module__ = 'packet_id_allocate_pb2'
  # @@protoc_insertion_point(class_scope:table.Packet_id_allocate)
  ))
_sym_db.RegisterMessage(Packet_id_allocate)

Packet_id_allocateItem = _reflection.GeneratedProtocolMessageType('Packet_id_allocateItem', (_message.Message,), dict(
  DESCRIPTOR = _PACKET_ID_ALLOCATEITEM,
  __module__ = 'packet_id_allocate_pb2'
  # @@protoc_insertion_point(class_scope:table.Packet_id_allocateItem)
  ))
_sym_db.RegisterMessage(Packet_id_allocateItem)


# @@protoc_insertion_point(module_scope)
